USE prub

CREATE TABLE IF NOT EXISTS Caso
(
Id INT (11) NOT NULL AUTO_INCREMENT,
Nombre VARCHAR(15) NULL DEFAULT NULL,
Cedula INT(15) NULL DEFAULT NULL,
Fecha DATETIME NULL DEFAULT NULL,
 Robo VARCHAR(100) NULL DEFAULT NULL,
 Valor DOUBLE NULL DEFAULT NULL,
 Sitio VARCHAR(100) NULL DEFAULT NULL,
 Latitud VARCHAR(100) NULL DEFAULT NULL,
 Longitud VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`Id`) 
)

SELECT * FROM caso